### ISSUE TITLE
wg(4): handshake response has src and dst reversed

### ISSUE THREAD

**Issue by cheggerdev** [opnsense/src#268]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hello,

This is my forum post: https://forum.opnsense.org/index.php?topic=49524.0
I am coming here because I think the issue requires help from a kernel (driver) developer and I do not know if they read the user forum.

**Comment by Monviech** [comment]
Hello,

if this is indeed a wg kernel driver issue you have to go way further upstream to eg the freebsd issue tracker.

https://bugs.freebsd.org/bugzilla/

**Comment by cheggerdev** [comment]
Upstream bugreport https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=290768

Please leave this open for when it comes to pulling in fixes into OpnSense.

**Comment by cheggerdev** [comment]
If FreeBSD developers are going to provide "a custom kernel with more diagnostics" what are the build options they should use that the kernel works with opnsense ?

What would be the best way to install / boot the custom kernel ?
How can I revert back to original kernel after testing ? Would be reinstalling the kernel package sufficient ?

FYI: I installed opnsense with zfs on disk.

**Comment by Monviech** [comment]
Reading the comment it sounds like they want you to install a vanilla FreeBSD 15 and try to recreate the same issue on that.

Essentially you would only need wireguard and the carp configuration on such a machine.

Though it seems like they referenced one commit, so maybe @fichtner can help.

**Comment by cheggerdev** [comment]
> Though it seems like they referenced one commit, so maybe [@fichtner](https://github.com/fichtner) can help.

@fichtner Are you able to provide a custom kernel package with the referenced commit cherry-picked (see https://github.com/opnsense/src/issues/268#issuecomment-3480578412)?

**Comment by fichtner** [comment]
I'm currently blocked from participating in FreeBSD bugzilla so I need to phrase the question here:

Is the commit a supposed fix or not? It's not clear to me. Would like to double check before building the wrong thing. CC @kevans91

**Comment by kevans91** [comment]
> I'm currently blocked from participating in FreeBSD bugzilla so I need to phrase the question here:
> 
> Is the commit a supposed fix or not? It's not clear to me. Would like to double check before building the wrong thing. CC [@kevans91](https://github.com/kevans91)

I suspect it might be, but I can't say with confidence at the moment.  At the very least, it's the only thing I can see that could be overriding or messing up our source/destination, so I would like to see if it's still a problem after that's been cherry-picked and subsequently insert some diagnostic prints to try and track down where it's going wrong.

**Comment by fichtner** [comment]
Sounds good. Built as per 45513de39cfda5f898f8 to install via:

    # opnsense-update -zkr 25.7.5-wg_bug

Requires reboot.

Disclaimer: I have not test-booted this but other than that commit the previous builds have been verified by multiple users over the last few weeks so I expect minimal chance for problems arising.


Cheers,
Franco

**Comment by cheggerdev** [comment]
@fichtner @kevans91 Thank you. I tested the kernel. Test report is in FreeBSD bugzilla.

**Comment by fichtner** [comment]
cool, let me know what else you guys want to test here.... cannot subscribe over there at the moment ;)

**Comment by kevans91** [comment]
> cool, let me know what else you guys want to test here.... cannot subscribe over there at the moment ;)

If you could build a test kernel with this applied on top of that: https://bz-attachments.freebsd.org/attachment.cgi?id=265312  -- I don't think it'll fix the entire problem, but it fixes one problem I noticed tracing through the sosend() path.

**Comment by fichtner** [comment]
sure :) so that's 736edd4 via:

    # opnsense-update -zkr 25.7.5-wg_bug2


Cheers,
Franco

**Comment by cheggerdev** [comment]
@fichtner @kevans91 Thank you again. I tested the kernel 25.7.5-wg_bug2. Test report is in FreeBSD bugzilla.

**Comment by kevans91** [comment]
> [@fichtner](https://github.com/fichtner) [@kevans91](https://github.com/kevans91) Thank you again. I tested the kernel 25.7.5-wg_bug2. Test report is in FreeBSD bugzilla.

Can you try again initiating from the peer and add relevant lines from `pfctl -s states` for a.b.c.d, please?

**Comment by cheggerdev** [comment]
> Can you try again initiating from the peer and add relevant lines from `pfctl -s states` for a.b.c.d, please?

all udp 192.168.178.2:51820 <- a.b.c.d:23423       NO_TRAFFIC:SINGLE
all udp a.b.c.d:23423 -> 192.168.178.2:51820       SINGLE:NO_TRAFFIC

**Comment by cheggerdev** [comment]
@fichtner Could you please rebase to 25.7.8 and then build a new kernel with https://bugs.freebsd.org/bugzilla/attachment.cgi?id=265617&action=diff applied on top of wg_bug2? Thanks.

**Comment by cheggerdev** [comment]
@fichtner ping (I cannot crossbuild an OpnSense Kernel on OSX)

**Comment by cheggerdev** [comment]
On bugzilla came up a question (comment 25):

> Was PF or IPFW used? Or perhaps IPF in this case ?

What exactly does OpnSense use behind the WebGUI ?

**Comment by Monviech** [comment]
It uses pf for filter/nat/scrub and ipfw for dummynet shaper (if shaper rules are enabled)

**Comment by cheggerdev** [comment]
The setup I do via WebGUI is this:

Install & setup Wireguard instance on an wg interface.
Add a CARP virtual IP to your ethernet interface (your outgoing interface if you have more than one).
Add an outgoing NAT rule that does Source NAT from your ethernet IP address to your CARP address.

Setup a Wireguard peer using the peer generator. Do **not** set the peers endpoint afterwards.

What exactly happens on CLI when I do the above steps in the WebGUI ?
A request from bugzilla is to bring up a *scripted way* to reproduce.

**Comment by Monviech** [comment]
A scripted way to reproduce this is a challenging concept.

What I think would be expected is a FreeBSD host with jails and epair.

Inside that, two jails could be created via scripts, these configure: 
- Their own ip addresses via ifconfig
- CARP address via ifconfig
- wg-quick (or ifconfig wg) commands to bring up wg tunnels
- pfctl commands to load a specific ruleset into PF

With this setup one can connect inside these jails and do the tests, or even write an automated test case.

But this is pretty high level stuff for a bug report in my opinion.

**Comment by cheggerdev** [comment]
> A scripted way to reproduce this is a challenging concept.

Yes, it is.

> What I think would be expected is a FreeBSD host with jails and epair.
 
This can be further simplified because I already figured out that a CARP master only with one ethernet interface is necessary to reproduce.

**Comment by cheggerdev** [comment]
@fichtner Could you please rebase the wg_bug branch to 25.7.8 and (re)build the packages 25.7.8-wg_bug and 25.7.8-wg_bug2.
Then apply patch [1]  on top of it and build 25.7.8-wg_bug3.
Then cherry pick two PF patches [2] and [3] and build 25.7.8-wg_bug4.

[1] https://bugs.freebsd.org/bugzilla/attachment.cgi?id=265617&action=diff
[2] https://cgit.freebsd.org/src/commit/sys?id=c12013f5bb3819e64499f02ecd199a635003c7ce
[3] https://cgit.freebsd.org/src/commit/sys?id=7dedc3c21436bb5a1220f8901992d2772a163f78

**Comment by fichtner** [comment]
I've built the kernel with [1] now:

    # opnsense-update -zkr 25.7.5-wg_bug3

As far as [2] and [3] go: they don't apply to stable/14 and are not on stable/14. If FreeBSD thinks they are bug fixes I'd appreciate reconsidering the stance to _not_ cherry-pick all sorts of pf fixes to stable/14 for no apparent reason. :)

And sorry for the delay. We're trying to run a project here and had an intricate release week.


Cheers,
Franco

**Comment by cheggerdev** [comment]
@fichter Thank you very much. I supposed you were busy because of the 25.7.8 release.

I tested the wg_bug3 kernel. Now there is confidence that the family address is 0 in the sosend() path.

**Comment by kevans91** [comment]
We should have perhaps requested all of these builds to turn on INVARIANTS, or at least `INVARIANT_SUPPORT` in the kernel and build the wg kmod with INVARIANTS enabled.  I'm taking a look at this send path some more -- the assertion in wg_peer_set_endpoint() probably would have caught the bogus peer endpoint sooner if we're not looking at something else coming in and clobbering it after the fact.

**Comment by fichtner** [comment]
I can easily offer the debug kernel we have, see https://github.com/opnsense/tools/blob/master/config/25.7/kernel.debug

    # opnsense-update -zkr dbg-25.7.5-wg_bug3


Cheers,
Franco

**Comment by kevans91** [comment]
> I can easily offer the debug kernel we have, see https://github.com/opnsense/tools/blob/master/config/25.7/kernel.debug
> 
> ```
> # opnsense-update -zkr dbg-25.7.5-wg_bug3
> ```
> 
> Cheers, Franco

Oh, perfect, thanks!  @cheggerdev please give this a shot and let's see if you end up tripping an assertion somewhere along the way.

**Comment by cheggerdev** [comment]
Sure. I tried and I triggert **no** assertion.
dmesg shows:

wg1: Handshake for peer 1 did not complete after 5 seconds, retrying (try 2)
wg1: Sending handshake initiation to peer 1
wg1: wg_send: Unknown family: 0
wg1: Unable to send packet: 47

**Comment by kevans91** [comment]
Fascinating- there's an assertion in `wg_peer_set_endpoint` that the family isn't 0 and that would have been called prior to the initial `wg_send_initiation` call, so there's something funky going on.

**Comment by cheggerdev** [comment]
> Fascinating- there's an assertion in `wg_peer_set_endpoint` that the family isn't 0 and that would have been called prior to the initial `wg_send_initiation` call, so there's something funky going on.

... **if** `wg_peer_set_endpoint` is called at all ...
a DPRINTF therein would clarify.

**Comment by kevans91** [comment]
> > Fascinating- there's an assertion in `wg_peer_set_endpoint` that the family isn't 0 and that would have been called prior to the initial `wg_send_initiation` call, so there's something funky going on.
> 
> ... **if** `wg_peer_set_endpoint` is called at all ... a DPRINTF therein would clarify.

There shouldn't really be a way to get to sending an initiation without having called it, but that's a fair point. Are you setting the debug flag on the interface prior to trying the handshake from the remote side, by the way? (I think we're missing some debug output from the initial response attempt)

**Comment by cheggerdev** [comment]
> > > Fascinating- there's an assertion in `wg_peer_set_endpoint` that the family isn't 0 and that would have been called prior to the initial `wg_send_initiation` call, so there's something funky going on.
> > 
> > 
> > ... **if** `wg_peer_set_endpoint` is called at all ... a DPRINTF therein would clarify.
> 
> There shouldn't really be a way to get to sending an initiation without having called it, but that's a fair point. Are you setting the debug flag on the interface prior to trying the handshake from the remote side, by the way? (I think we're missing some debug output from the initial response attempt)

Yes, I do. I set the debug flag and then I start the handshake from the peer.
And yes, we miss all debug outputs from the initial response. I think, we are not getting there because of the `wg1: Unable to send packet: 47` debug message.
I suggest to sprinkle more assertions and DPRINTF's.

**Comment by cheggerdev** [comment]
Does the kernel remember the handshake even across reboot ?
After a boot/reboot I still see in dmesg **without** initiating anything from the peer:

wg1: Handshake for peer 1 did not complete after 5 seconds, retrying (try 2)
wg1: Sending handshake initiation to peer 1
wg1: wg_send: Unknown family: 0
wg1: Unable to send packet: 47

Or is this coming from bringing up the wgX interface ?

**Comment by kevans91** [comment]
> Does the kernel remember the handshake even across reboot ? After a boot/reboot I still see in dmesg **without** initiating anything from the peer:
> 
> wg1: Handshake for peer 1 did not complete after 5 seconds, retrying (try 2) wg1: Sending handshake initiation to peer 1 wg1: wg_send: Unknown family: 0 wg1: Unable to send packet: 47
> 
> Or is this coming from bringing up the wgX interface ?

Hmm, maybe. Is persistent-keepalive set?

**Comment by cheggerdev** [comment]
> > Does the kernel remember the handshake even across reboot ? After a boot/reboot I still see in dmesg **without** initiating anything from the peer:
> > wg1: Handshake for peer 1 did not complete after 5 seconds, retrying (try 2) wg1: Sending handshake initiation to peer 1 wg1: wg_send: Unknown family: 0 wg1: Unable to send packet: 47
> > Or is this coming from bringing up the wgX interface ?
> 
> Hmm, maybe. Is persistent-keepalive set?

Yes, in the peer configuration.

**Comment by kevans91** [comment]
We would want something like [0] to keep it from trying to handshake immediately if the endpoint isn't set but persistent-keepalive was -- patch not really tested, but it's fairly straightforward.

[0] https://people.freebsd.org/~kevans/wg-keepalive.diff

**Comment by kevans91** [comment]
The final form of this patch is going to want to touch `wg_peer_add` as well, to run persistent keepalive if the endpoint becomes set.

**Comment by cheggerdev** [comment]
@fichtner Please provide a new kernel including debug variant with wg-keepalive.diff from @kevans91

**Comment by fichtner** [comment]
# opnsense-update -zkr dbg-25.7.5-wg_bug4

**Comment by kevans91** [comment]
It seems this last one is actually not really a bug; Linux will apparently do the same to keep things simple, since it's harmless (the resulting packets just get dropped because there's no destination)

**Comment by cheggerdev** [comment]
> ```
> # opnsense-update -zkr dbg-25.7.5-wg_bug4
> ```

With this I see nothing in dmesg. Nothing after boot and nothing after I initiated handshake from the peer.
In tcpdump I see

```
19:00:34.416053 IP a.b.c.d.47305 > 10.2.1.30.51820: UDP, length 148
19:00:34.416057 IP a.b.c.d.47305 > 10.2.1.30.51820: UDP, length 148
19:00:34.418392 IP a.b.c.d.47305 > 10.2.1.30.51820: UDP, length 148
```

pfctl -s states | grep 51820
all udp 10.2.1.30:51820 <- a.b.c.d:45350       NO_TRAFFIC:SINGLE
all udp a.b.c.d:45350 -> 10.2.1.30:51820       SINGLE:NO_TRAFFIC

No assertion is triggert.

**Comment by kevans91** [comment]
OK, so we don't seem to be getting the handshake initiation into wg(4) at all.  I wonder if the port forwarding is subverting UDP tunneling somehow.  Did the pre-CARP configuration require port forwarding as well, or was that just a rule to allow inbound UDP on that port?

**Comment by cheggerdev** [comment]
> OK, so we don't seem to be getting the handshake initiation into wg(4) at all. I wonder if the port forwarding is subverting UDP tunneling somehow. Did the pre-CARP configuration require port forwarding as well, or was that just a rule to allow inbound UDP on that port?

In my testbed there is no port forwarding at all.
In the production env the port forwarding is just a gateway rule to allow inbound UDP on that port from the internet.

**Comment by kevans91** [comment]
> > OK, so we don't seem to be getting the handshake initiation into wg(4) at all. I wonder if the port forwarding is subverting UDP tunneling somehow. Did the pre-CARP configuration require port forwarding as well, or was that just a rule to allow inbound UDP on that port?
> 
> In my testbed there is no port forwarding at all. In the production env the port forwarding is just a gateway rule to allow inbound UDP on that port from the internet.

What kind of pf configuration do you have in the testbed, particularly for inbound traffic? I haven't been able to reproduce in a jail locally with just CARP over epair, but maybe I need another interface involved.

**Comment by cheggerdev** [comment]
I enlist the rules here not in pfctl syntax but the way they read in the WebGUI.

OpnSense has automatically generated rules:

Block in quick all IPv6 traffic
Block in last match IPv4+6 traffic description "Default deny / state violation rule"
Block in quick IPv4+6 TCP/UDP source port 0 destination any
Block in quick IPv4+6 TCP/UDP source any destination port 0
Pass any direction quick IPv4 CARP source any destination 224.0.0.18 description "CARP defaults"
Block in quick IPv4+6 source <sshlockout> destination (self) 22 description "sshlockout"
Block in quick IPv4+6 source <sshlockout> destination (self) 443 description "sshlockout"
Block in quick IPv4+6 source <virusprot> destination any description "virusprot overload table"
Block in quick IPv4+6 source <bogons> destination any description "Block bogon IPv4 networks from igc0_WAN"
Pass out last match IPv4+6 source any destination any description "let out anything from firewall host itself"

The following "floating" rules that apply on all interfaces:
Block out quick IPv6 source any destination any description "Block outgoing IPv6 traffic"
Pass in quick IPv4 TCP/UDP source LAN destination This firewall ports 10050, 10051 (Zabbix)
Pass in quick IPv4 UDP source LAN destination This firewall ports 67, 68 (DHCP)
Pass in quick IPv4 TCP/UDP source LAN destination This firewall port 53 (DNS)

WAN specific rules:
Pass in quick on igc0 IPv4 CARP source any destination any
Pass in quick on igc0 IPv4 UDP source any destination igc0 address port 51820 gateway  Internet-Gateway Address
Pass in quick on igc0 IPv4 TCP source any destination This firewall port 22 (SSH)

**Comment by cheggerdev** [comment]
@fichtner Could you please check if FreeBSD 14-stable has any pf patches OpnSense does **not** have?
If so, could you please enlist them here and cherry pick and build a new debug kernel ?

**Comment by kevans91** [comment]
> Pass in quick on igc0 IPv4 UDP source any destination igc0 address port 51820 gateway Internet-Gateway Address

What happens if you widen that from igc0 to "this firewall" in general?

**Comment by cheggerdev** [comment]
> > Pass in quick on igc0 IPv4 UDP source any destination igc0 address port 51820 gateway Internet-Gateway Address
> 
> What happens if you widen that from igc0 to "this firewall" in general?

@kevans91 Makes no difference.
I forgot one thing: I have an normalization rule bound to the wg interfaces.
mss-clamping (max mss) value 1372 source any destination any 

In the production env the gateway does PPPoE for the internet connection.

@Monviech @fichtner When I specify an interface address on the WebGUI does it include or exclude the attached CARP address?

**Comment by cheggerdev** [comment]
> [@kevans91](https://github.com/kevans91) Makes no difference. I forgot one thing: I have an normalization rule bound to the wg interfaces. mss-clamping (max mss) value 1372 source any destination any

I tested without normalization. No difference.

**Comment by kevans91** [comment]
Can you toggle logging an all of your pf rules and confirm via logs that pf isn't somehow getting in our way, before we try any more patches with more diagnostics?

**Comment by cheggerdev** [comment]
> Can you toggle logging an all of your pf rules and confirm via logs that pf isn't somehow getting in our way, before we try any more patches with more diagnostics?

Done. This is all I see:

igc0_WAN Out 2025-12-02T17:32:31 UDP a.b.c.d:58690 10.2.1.30:51820 pass let out anything from firewall host itself
igc0_WAN In 2025-12-02T17:32:31 UDP a.b.c.d:58690 10.2.1.30:51820 pass Allow to connect to Wireguard Server

**Comment by kevans91** [comment]
> > Can you toggle logging an all of your pf rules and confirm via logs that pf isn't somehow getting in our way, before we try any more patches with more diagnostics?
> 
> Done. This is all I see:
> 
> igc0_WAN Out 2025-12-02T17:32:31 UDP a.b.c.d:58690 10.2.1.30:51820 pass let out anything from firewall host itself igc0_WAN In 2025-12-02T17:32:31 UDP a.b.c.d:58690 10.2.1.30:51820 pass Allow to connect to Wireguard Server

That's... quite confusing?  Assuming this is from the opnsense table and you didn't swap the source/destination, the `Out` line seems to be backwards despite the previously-cherrypicked commit that should have fixed that?

That also doesn't really seem to line up with your previous observations in https://github.com/opnsense/src/issues/268#issuecomment-3591842816; if we generated a packet to sent out from the firewall hot, then we should have *something* in dmesg if the debug flag was set on the wireguard interface.

**Comment by cheggerdev** [comment]
> That's... quite confusing? Assuming this is from the opnsense table and you didn't swap the source/destination, the `Out` line seems to be backwards despite the previously-cherrypicked commit that should have fixed that?
> 
> That also doesn't really seem to line up with your previous observations in [#268 (comment)](https://github.com/opnsense/src/issues/268#issuecomment-3591842816); if we generated a packet to sent out from the firewall hot, then we should have _something_ in dmesg if the debug flag was set on the wireguard interface.

For (better) comparising I installed the vanilla OpnSense **25.7.8** kernel without any extra patches.
There I get this:

igc0_WAN Out 2025-12-03T08:45:50 UDP a.b.c.d:53679 10.2.1.30:51820 pass let out anything from firewall host itself
igc0_WAN In 2025-12-03T08:45:50 UDP a.b.c.d:53679 10.2.1.30:51820 pass Allow to connect to Wireguard Server

pfctl -s states | fgrep 51820
all udp 10.2.1.30:51820 <- a.b.c.d:53679       NO_TRAFFIC:SINGLE
all udp a.b.c.d:53679 -> 10.2.1.30:51820       SINGLE:NO_TRAFFIC


Then again with the vanilla OpnSense **25.7.5** kernel without any extra patches:

igc0_WAN Out 2025-12-03T08:54:14 UDP a.b.c.d:44877 10.2.1.30:51820 pass let out anything from firewall host itself
igc0_WAN In 2025-12-03T08:54:14 UDP a.b.c.d:44877 10.2.1.30:51820 pass Allow to connect to Wireguard Server

pfctl -s states | fgrep 51820
all udp 10.2.1.30:51820 <- a.b.c.d:44877       NO_TRAFFIC:SINGLE
all udp a.b.c.d:44877 -> 10.2.1.30:51820       SINGLE:NO_TRAFFIC


Then again with the **25.7.5-wg_bug4** kernel:

igc0_WAN Out 2025-12-03T09:04:32 UDP a.b.c.d:51600 10.2.1.30:51820 pass let out anything from firewall host itself
igc0_WAN In 2025-12-03T09:04:32 UDP a.b.c.d:51600 10.2.1.30:51820 pass Allow to connect to Wireguard Server

pfctl -s states | fgrep 51820
all udp 10.2.1.30:51820 <- a.b.c.d:51600       NO_TRAFFIC:SINGLE
all udp a.b.c.d:51600 -> 10.2.1.30:51820       SINGLE:NO_TRAFFIC


Then again with the **25.7.5-wg_bug2** kernel that has the UDP patch only:

igc0_WAN Out 2025-12-03T14:26:06 UDP a.b.c.d:45013 10.2.1.30:51820 pass let out anything from firewall host itself
igc0_WAN In 2025-12-03T14:26:06 UDP a.b.c.d:45013 10.2.1.30:51820 pass Allow to connect to Wireguard Server

pfctl -s states | fgrep 51820
all udp 10.2.1.30:51820 <- a.b.c.d:45013       NO_TRAFFIC:SINGLE
all udp a.b.c.d:45013 -> 10.2.1.30:51820       SINGLE:NO_TRAFFIC


Important notice:   OpnSense Live View shows the traffic in descendent order (newest is at the top). That means the igc0_WAN In comes **before** the igc0_WAN Out.

It looks like I was confused after testing the UDP patch.

**Comment by cheggerdev** [comment]
> For (better) comparising I installed the vanilla OpnSense **25.7.8** kernel without any extra patches. There I get this:

I repeated this again. This time I show what I get with  `wg show`, with tcpdump and with dmesg

With OpnSense **25.7.8** kernel:

tcpdump:

15:28:35.303080 IP a.b.c.d.57814 > 10.2.1.30.51820: UDP, length 148
15:28:35.304207 IP a.b.c.d.57814 > 10.2.1.30.51820: UDP, length 148
15:28:35.304221 IP a.b.c.d.57814 > 10.2.1.30.51820: UDP, length 148
15:28:35.304818 IP a.b.c.d.57814 > 10.2.1.30.51820: UDP, length 148
15:28:35.304826 IP a.b.c.d.57814 > 10.2.1.30.51820: UDP, length 148

wg show

peer: <secret>
  allowed ips: 10.251.0.4/32
  transfer: 0 B received, 5.78 KiB sent
  persistent keepalive: every 30 seconds

dmesg

[36] wg1: Sending handshake initiation to peer 1
[36] wg1: Unable to send packet: 47
[36] wg1: Handshake for peer 3 did not complete after 5 seconds, retrying (try 5)
[36] wg1: Sending handshake initiation to peer 3


Then again with the vanilla OpnSense **25.7.5** kernel without any extra patches:

tcpdump:

15:36:43.180498 IP a.b.c.d.54982 > 10.2.1.30.51820: UDP, length 148
15:36:43.180510 IP a.b.c.d.54982 > 10.2.1.30.51820: UDP, length 148
15:36:43.181280 IP a.b.c.d.54982 > 10.2.1.30.51820: UDP, length 148
15:36:43.181284 IP a.b.c.d.54982 > 10.2.1.30.51820: UDP, length 148
15:36:43.181984 IP a.b.c.d.54982 > 10.2.1.30.51820: UDP, length 148
 
wg show:

peer: <secret>
  allowed ips: 10.251.0.4/32
  transfer: 0 B received, 1.59 KiB sent
  persistent keepalive: every 30 seconds

dmesg:

[144] wg1: Sending keepalive packet to peer 1
[144] wg1: Sending handshake initiation to peer 1
[144] wg1: Unable to send packet: 47

Then again with the **25.7.5-wg_bug2** kernel that has the UDP patch only:

tcpdump:

15:45:31.879238 IP a.b.c.d.42369 > 10.2.1.30.51820: UDP, length 148
15:45:31.879876 IP a.b.c.d.42369 > 10.2.1.30.51820: UDP, length 148
15:45:31.879891 IP a.b.c.d.42369 > 10.2.1.30.51820: UDP, length 148
15:45:31.880582 IP a.b.c.d.42369 > 10.2.1.30.51820: UDP, length 148
15:45:31.880593 IP a.b.c.d.42369 > 10.2.1.30.51820: UDP, length 148

wg show:

peer: <secret>
  allowed ips: 10.251.0.4/32
  transfer: 0 B received, 1.88 KiB sent
  persistent keepalive: every 30 seconds

dmesg:

[143] wg1: Sending keepalive packet to peer 1
[143] wg1: Sending handshake initiation to peer 1
[143] wg1: Unable to send packet: 47


Then again with the **25.7.5-wg_bug4** kernel:

tcpdump:

15:50:47.913526 IP a.b.c.d.58928 > 10.2.1.30.51820: UDP, length 148
15:50:47.915898 IP a.b.c.d.58928 > 10.2.1.30.51820: UDP, length 148
15:50:47.915906 IP a.b.c.d.58928 > 10.2.1.30.51820: UDP, length 148
15:50:47.916642 IP a.b.c.d.58928 > 10.2.1.30.51820: UDP, length 148
15:50:47.916657 IP a.b.c.d.58928 > 10.2.1.30.51820: UDP, length 148

wg show:

peer: <secret>
  allowed ips: 10.251.0.4/32
  persistent keepalive: every 30 seconds

dmesg:

No output.

**Comment by kevans91** [comment]
If you can figure out how to reproduce this on stock FreeBSD (from a stable/14 snapshot), that'd be really helpful to try and progress this.  I can only really work on wg(4) in my spare time, and that spare time is limited enough that having to try and reproduce your opnsense setup locally (and in a way that I can really debug without having to bother Franco) is somewhat prohibitive.  That's not to say I won't spend time thinking about this, just that it falls a bit lower on the priority list for me because of the added complexity.

**Comment by kevans91** [comment]
I guess, alternatively, if you can produce a VM image or something that reproduces it easily enough that you'd be willing to share with me, I can probably figure out the opnsense build system enough to debug it locally.

**Comment by cheggerdev** [comment]
I can offer the opnsense configuration file of my testbed.
See comment 32 on bugzilla.

**Comment by fichtner** [comment]
I wonder if testing a 15.0 kernel now that it has been released would give reasonable results that this may have been fixed? As I said stable/14 is a bit unreliable and inflexible in my opinion. That would take a bit of burden off of @kevans91

**Comment by cheggerdev** [comment]
> I wonder if testing a 15.0 kernel now that it has been released would give reasonable results that this may have been fixed? As I said stable/14 is a bit unreliable and inflexible in my opinion. That would take a bit of burden off of [@kevans91](https://github.com/kevans91)

That would be great. What `opnsense-update` command do I have to run to get the 15.0 kernel ?

**Comment by fichtner** [comment]
let me try and see if I can cook up a kernel on the spot, likely tomorrow if it goes well

**Comment by kevans91** [comment]
> I wonder if testing a 15.0 kernel now that it has been released would give reasonable results that this may have been fixed? As I said stable/14 is a bit unreliable and inflexible in my opinion. That would take a bit of burden off of [@kevans91](https://github.com/kevans91)

Yeah, that'd be a really good datapoint- tracking down where it might have been fixed (if it works) might prove a little tricky, but it would certainly be good to know if this could be OBE within the next year or so.

**Comment by fichtner** [comment]
Booted this on my main box and it looks usable. I can't vouch for any edge cases that require our patches.

    # opnsense-update -zkr 15.0 -a FreeBSD:15:amd64

> tracking down where it might have been fixed (if it works) might prove a little tricky

True. Perhaps also unnecessary if we can adopt 15.1 in 26.7. It's about 7 more months, but they usually fly by quickly. :)


Cheers,
Franco

**Comment by cheggerdev** [comment]
Thank you. I tested and I can still reproduce the issue. See bugzilla comment 33 for result.
@fichtner Is this a debug kernel ? I cannot trigger any assertions.
I suppose not because `opnsense-update -zkr dbg-15.0 -a FreeBSD:15:amd64` fails because of missing signature.

@fichtner How do you build the 15.0 kernel ? Can you share instructions with us starting from a fresh standard opnsense install to build and install a new kernel locally ?

That will help debugging.

**Comment by fichtner** [comment]
Debug kernel now at

    # opnsense-update -zkr dbg-15.0 -a FreeBSD:15:amd64

Haven't tested it.

Building locally through https://github.com/opnsense/tools is advised, but we don't have a proper branch for 15 yet and it can be difficult to navigate the caveats. It's possible to coerce the build by removing the SMP kernel options for `GEOM_BDE` and `TCP_SAD_DETECTION`. The resulting file is a kernel.txz equivalent that simply unpacks on `/` given you moved `/boot/kernel` out of the way first, e.g. `/boot/kernel.old`.

A debug kernel is built with `DEBUG=yes` added to the command line.


Cheers,
Franco

**Comment by cheggerdev** [comment]
> Debug kernel now at
> 
> ```
> # opnsense-update -zkr dbg-15.0 -a FreeBSD:15:amd64
> ```

Awesome!

> Haven't tested it.

I did. It boots. Reproduced the issue. No assertion triggered.

**Comment by cheggerdev** [comment]
> Building locally through https://github.com/opnsense/tools is advised, but we don't have a proper branch for 15 yet and it can be difficult to navigate the caveats. It's possible to coerce the build by removing the SMP kernel options for `GEOM_BDE` and `TCP_SAD_DETECTION`. The resulting file is a kernel.txz equivalent that simply unpacks on `/` given you moved `/boot/kernel` out of the way first, e.g. `/boot/kernel.old`.
> 
> A debug kernel is built with `DEBUG=yes` added to the command line.

Thank you.
I successfully built a 14.3 kernel:

```
cd $HOME
mkdir -p opnsense
git clone https://github.com/opnsense/tools
git clone https://github.com/opnsense/src
cd tools
env ROOTDIR=$HOME/opnsense make -j 8 kernel DEBUG=yes
```

```
Build result:
/usr/obj/$ROOTDIR/src/amd64.amd64/release/kernel-dbg.txz
/usr/obj/$ROOTDIR/src/amd64.amd64/release/kernel.txz
```

And successfully booted it.


Update:

Faster **re**build without cleaning the entire kernel everytime:

```
cd $HOME/opnsense/src
env ROOTDIR=$HOME/opnsense DEBUG=yes make -j 8 -DNO_CLEAN kernel
```

**Comment by kevans91** [comment]
Excellent, thanks for the information (both of you).  I'll try to find some time in the next few weeks to pursue the mystery a bit further locally.

**Comment by cheggerdev** [comment]
I sprinkled some DPRINTF's in wg(4).

```
@@ -2914,14 +2921,17 @@ wg_up(struct wg_softc *sc)
        if ((sc->sc_flags & WGF_DYING) != 0)
                goto out;
 
+       DPRINTF(sc, "%s A\n", __func__);
        /* Silent success if we're already running. */
        rc = 0;
        if (if_getdrvflags(ifp) & IFF_DRV_RUNNING)
                goto out;
        if_setdrvflagbits(ifp, IFF_DRV_RUNNING, 0);
 
+       DPRINTF(sc, "%s B\n", __func__);
        rc = wg_socket_init(sc, sc->sc_socket.so_port);
        if (rc == 0) {
+               DPRINTF(sc, "%s C\n", __func__);
                TAILQ_FOREACH(peer, &sc->sc_peers, p_entry)
                        wg_timers_enable(peer);
                if_link_state_change(sc->sc_ifp, LINK_STATE_UP);
```

Then after boot in dmesg all I see is:

```
[9] wg1: link state changed to UP
[10] wg1: wg_up A
[10] wg1: wg_up A
[10] wg1: wg_up A
```

I never see B or C. Also after reproducing the issue I see no more output. No more A, no more B, no more C.
In wg_socket_init() I also sprinkled some DPRINTF()'s but I never see them.

**Comment by cheggerdev** [comment]
I digged deeper with if_printf() and printf().

wg_socket_init() runs with port 0 and for each wg interface with the correct listening port.
udp_set_kernel_tunneling() registers wg_input().
But when udp_append() is called it never calls the callback function u_tun_func that should point to wg_input().
It looks like u_tun_func pointer gets lost somewhere.

**Comment by kevans91** [comment]
This didn't seem to reproduce locally with your config, even with stable/25.7.   I did notably have s/igc0/vtnet0/ in the config, but you can see below that the CARP config remained intact.  I realized after re-evaluating this morning that I had also removed the gateway setting from the inbound rule for 51900, but playing around with other rules using the gateway setting my conclusion is that I just don't have the gateway setup correctly, somehow, which probably isn't the case for you -- alas, I'm stumped.  I confirmed that disabling the inbound rule for 51900 properly breaks the handshake, so unless the different network for CARP is the problem I'm unsure what to think.

```
vtnet0: flags=1008b43<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
        description: vtnet0_WAN (wan)
        options=880028<VLAN_MTU,JUMBO_MTU,LINKSTATE,HWSTATS>
        ether 58:9c:fc:02:18:ad
        inet 192.168.20.141 netmask 0xffffff00 broadcast 192.168.20.255
        inet 10.2.1.30 netmask 0xffff0000 broadcast 10.2.255.255 vhid 5
        carp: MASTER vhid 5 advbase 1 advskew 0
              peer 224.0.0.18 peer6 ff02::12
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
root@opnsense-wgbug:~ # pfctl -s rules | grep 51900
pass in log quick on vtnet0 inet proto udp from any to (self) port = 51900 keep state label "955385abf4e44599dda115daf4b3364a"
root@opnsense-wgbug:~ # wg show
interface: wg1
  public key: ti5keZav1CifCqjIWrxtFt0b7NG7EHcVhQyF3yO0cWg=
  private key: (hidden)
  listening port: 51900

peer: 19tVvD/qbHwVQcLB54NjSybLNXVS0Q2Sb1auzd4dbW0=
  endpoint: 192.168.20.1:57683
  allowed ips: 192.168.40.0/24
  latest handshake: 1 minute, 20 seconds ago
  transfer: 412 B received, 380 B sent
```

**Comment by kevans91** [comment]
Actually, looking at what the 'gateway' setting seems to do to the underlying config, I don't see where that makes sense at all for a rule you expect to terminate at this firewall.

**Comment by cheggerdev** [comment]
> ```
>         inet 192.168.20.141 netmask 0xffffff00 broadcast 192.168.20.255
>         inet 10.2.1.30 netmask 0xffff0000 broadcast 10.2.255.255 vhid 5
>         carp: MASTER vhid 5 advbase 1 advskew 0
>               peer 224.0.0.18 peer6 ff02::12
> ```

The CARP address must be in the same subnet and must have the same netmask as the parent device.

> root@opnsense-wgbug:~ # pfctl -s rules | grep 51900
> pass in log quick on vtnet0 inet proto udp from any to (self) port = 51900 keep state label "955385abf4e44599dda115daf4b3364a"
> root@opnsense-wgbug:~ # wg show
> interface: wg1
>   public key: ti5keZav1CifCqjIWrxtFt0b7NG7EHcVhQyF3yO0cWg=
>   private key: (hidden)
>   listening port: 51900
> 
> peer: 19tVvD/qbHwVQcLB54NjSybLNXVS0Q2Sb1auzd4dbW0=
>   endpoint: 192.168.20.1:57683
>   allowed ips: 192.168.40.0/24
>   latest handshake: 1 minute, 20 seconds ago
>   transfer: 412 B received, 380 B sent
> ```

Did you configure the peer's endpoint via ioctl ?
I don't do that.

**Comment by kevans91** [comment]
No, I used the UI. I don't think either of these things changes the fact that you sent over a config that simply can't work out of the box because setting a gateway on the inbound rules will screw up those packets destined for the local machine (in my testing), but I'''ll fix the CARP config when I get back home

**Comment by cheggerdev** [comment]
The big picture behind the CARP setup is to have a High Availability setup with CARP (just heavily stripped down to track this issue):

https://docs.opnsense.org/manual/hacarp.html
https://docs.opnsense.org/manual/how-tos/carp.html

For this issue the outbound NAT is most interesting:
https://docs.opnsense.org/manual/how-tos/carp.html#setup-outbound-nat

From the picture shown in https://docs.opnsense.org/manual/how-tos/carp.html#overview
the config file should bring up the carp master with the WAN part only, nothing else.

What I want to do in the production environment in the end is the High Availability setup **combined** with
the Wireguard Road Warrior Setup: https://docs.opnsense.org/manual/how-tos/wireguard-client.html
The word **combined** is most important because that is where this issue raised up.

**Comment by cheggerdev** [comment]
In case you are interested in where I run OpnSense on:
https://www.amazon.de/HSIPC-Firewall-Appliance-Compatible-OPNsense/dp/B0B25QFYWB/?th=1

I have two of them.

**Comment by kevans91** [comment]
Right, I understand why CARP is useful in general, I've just never had to apply it.  I think we might be talking past each other, so I'm attaching a screenshot:

<img width="1203" height="636" alt="Image" src="https://github.com/user-attachments/assets/a12e02d4-88f4-4afc-a7db-0a84addf2394" />

I'm reasonably certain that your testing is invalid on any configuration where you have the gateway set to anything other than default.  It maps to the pf route-to option, which (based on testing with, e.g., a simple ssh rule) actively breaks any locally-destined trarffic -- it looks like it just tries to route the packet back out, which probably explains the original symptom of 'reversed' src/dst.  The UI probably shouldn't allow it for any destination that ultimately means 'this machine', I guess, if that's true.

**Comment by Monviech** [comment]
The route-to case is described here which also warns about the above:

https://docs.opnsense.org/manual/how-tos/multiwan.html#step-4-policy-based-routing

**Comment by cheggerdev** [comment]
Thank you for pointing this out.
I removed the Gateway and Wireguard works both in my Testbed and in my production env.

Sometimes in dmesg I see:

```
[9855] wg1: Packet has unallowed src IP from peer 0
```

although allowed IPs are: 0.0.0.0/0

My understanding was, **after** the packet comes out of wg(4) it should go to the given Gateway to survive a CARP failover.
But actually the packet is redirected to the given Gateway **before** it goes into wg(4), right?

My question is: Would the Wireguard VPN connection survive a CARP failover ?

Concerning the multiwan documentation is it possible to reference it in the wireguard and/or ha carp documentation ?

**Comment by Monviech** [comment]
Wireguard is a connectionless protocol, that means there is no connection that survives because there is none.

Its why the depend on carp option exists in the wireguard GUI to stop and start the service on mastwr and backup, only one of them should be started.

About the references of the pf gateway, quite impossible to document that everywhere, and there is also no input validation possible because there are no assumptions that could be made. E.g there is no way to validate that when selecting a gateway the destination of the rule cannot be the firewall, because "any" destination or any arbitrary IP could include it as destination implicitely.

It was just an operating error, it happens most with DNS and in multiwan thats why its at the correct spot in the documentation.

This was quite a wild goose chase but these issues are hard to find in complex systems.

**Comment by cheggerdev** [comment]
@kevans91 @fichtner With the native 25.7.8 kernel I get some noise in dmesg after a fresh boot:

```
[15] wg1: Handshake for peer 0 did not complete after 5 seconds, retrying (try 2)
[15] wg1: Sending handshake initiation to peer 0
[15] wg1: Unable to send packet: 47
```

I get this noise **before** I initiate a connection from the peer.

This patch [0] eliminates this noise. Please apply/commit it to FreeBSD 14/15 and OpnSense trees.

[0] https://people.freebsd.org/~kevans/wg-keepalive.diff

**Comment by fichtner** [comment]
@kevans91 will the above patch find its way into main at least? I don't see a problem picking it up from there.


Thanks,
Franco

**Comment by cheggerdev** [comment]
That would be great. It was that noise (in particular the error code 47 [0]) that made me think I run into a kernel issue.

[0] #define    EAFNOSUPPORT    47        /* Address family not supported by protocol family */


I want to thank you very much to all of you for your help.

**Comment by kevans91** [comment]
> [@kevans91](https://github.com/kevans91) will the above patch find its way into main at least? I don't see a problem picking it up from there.
> 
> Thanks, Franco

Negative- it was notably incomplete at the time. Consensus after having discussed it with other WireGuard folks is that this is how it operates on every platform, and the additional complexity to reduce small amounts of debugging noise isn't worth it -- it's pretty much the only way you can get that specific error.

**Comment by kevans91** [comment]
This is also an unusual use of persistent-keepalive. You wouldn't really use it often in this configuration because there's an inbound rule for external clients to establish the handshake, so unless this side is roaming it's just additional traffic for no clear reason. If it was needed on the other side (because it's roaming) then that would make sense over there, though, because this side may need to adjust its endpoint periodically.

**Comment by fichtner** [comment]
@kevans91 fair, thanks a lot for your time and input on this. highly appreciated!

**Comment by cheggerdev** [comment]
The description of this patch [0] sounds quite familiar :-D

[0] https://cgit.freebsd.org/src/commit/sys?id=42441d342071767f32cfe507466135dc79052a56

**Comment by cheggerdev** [comment]
> This is also an unusual use of persistent-keepalive. You wouldn't really use it often in this configuration because there's an inbound rule for external clients to establish the handshake, so unless this side is roaming it's just additional traffic for no clear reason. If it was needed on the other side (because it's roaming) then that would make sense over there, though, because this side may need to adjust its endpoint periodically.

The peer can actually do roaming. The peer can even be a mobile phone.

**Comment by kevans91** [comment]
> > This is also an unusual use of persistent-keepalive. You wouldn't really use it often in this configuration because there's an inbound rule for external clients to establish the handshake, so unless this side is roaming it's just additional traffic for no clear reason. If it was needed on the other side (because it's roaming) then that would make sense over there, though, because this side may need to adjust its endpoint periodically.
> 
> The peer can actually do roaming. The peer can even be a mobile phone.

Yes, keepalive holds very little value on the router side when it's the peer that's roaming.

**Comment by Monviech** [comment]
The keepalive is also explained here:

https://www.wireguard.com/quickstart/

NAT and Firewall Traversal Persistence section.

Btw I like how subtle they put "connections" into quotation marks xD

**Comment by cheggerdev** [comment]
@fichtner You may close https://forum.opnsense.org/index.php?topic=49524.0 as solved.

**Comment by fichtner** [comment]
@cheggerdev simply edit your first post and prepend `[SOLVED]` to the subject
